// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Blog struct {
	ID           uuid.UUID
	Title        string
	AuthorID     uuid.UUID
	ThumbnailUrl string
	Content      string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Category     uuid.UUID
}

type Category struct {
	ID           uuid.UUID
	CategoryName string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Collection struct {
	ID        uuid.UUID
	Name      string
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CollectionBlog struct {
	CollectionID uuid.UUID
	BlogID       uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Comment struct {
	ID          uuid.UUID
	Description string
	BlogID      uuid.UUID
	UserID      uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type CommentLike struct {
	UserID    uuid.UUID
	CommentID uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Like struct {
	UserID    uuid.UUID
	BlogID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type RefreshToken struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID             uuid.UUID
	Username       string
	Email          string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type UsersFollow struct {
	FollowerID  uuid.UUID
	FollowingID uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
